# Generated by Django 5.2.14 on 2026-05-13 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Frecuencia',
                'verbose_name_plural': 'Frecuencias',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('so', models.CharField(blank=True, max_length=200, verbose_name='Sistema operativo')),
            ],
            options={
                'verbose_name': 'Hardware',
                'verbose_name_plural': 'Hardware',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('seccion', models.CharField(blank=True, max_length=200, verbose_name='Sección o módulo')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('pasos', models.TextField(blank=True)),
                ('video_tutorial', models.CharField(blank=True, max_length=255, verbose_name='Video tutorial')),
            ],
            options={
                'verbose_name': 'Solución',
                'verbose_name_plural': 'Soluciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen_error', models.CharField(blank=True, max_length=500, verbose_name='Imagen del error')),
                ('usuario', models.CharField(blank=True, max_length=300, verbose_name='Usuario')),
                ('seccion_app', models.CharField(blank=True, max_length=300, verbose_name='Sección de App')),
                ('pruebas', models.TextField(blank=True, verbose_name='Pruebas')),
                ('causa', models.TextField(blank=True, verbose_name='Causa del problema')),
                ('solucion', models.TextField(blank=True, verbose_name='Solución o pasos para resolver')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('frecuencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores', to='errores.frecuencia')),
                ('hardware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores', to='errores.hardware')),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores', to='errores.sistema')),
            ],
            options={
                'verbose_name': 'Error',
                'verbose_name_plural': 'Errores',
                'ordering': ['id'],
            },
        ),
    ]
