# Generated by Django 5.2.14 on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


def cargar_modulos_desde_seccion(apps, schema_editor):
    Sistema = apps.get_model('errores', 'Sistema')
    Modulo = apps.get_model('errores', 'Modulo')

    for sistema in Sistema.objects.exclude(seccion=''):
        seccion = (sistema.seccion or '').strip()
        if seccion:
            Modulo.objects.get_or_create(sistema=sistema, nombre=seccion)


class Migration(migrations.Migration):

    dependencies = [
        ('errores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(db_column='prueba_tipica_id', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Prueba tipica',
                'verbose_name_plural': 'Pruebas tipicas',
                'db_table': 'prueba',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterModelOptions(
            name='solucion',
            options={'ordering': ['nombre'], 'verbose_name': 'Solucion', 'verbose_name_plural': 'Soluciones'},
        ),
        migrations.RenameField(
            model_name='solucion',
            old_name='video_tutorial',
            new_name='anexos',
        ),
        migrations.AlterField(
            model_name='solucion',
            name='anexos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='error',
            name='seccion_app',
            field=models.CharField(blank=True, max_length=300, verbose_name='Seccion de App'),
        ),
        migrations.AlterField(
            model_name='error',
            name='solucion',
            field=models.TextField(blank=True, verbose_name='Solucion o pasos para resolver'),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='id',
            field=models.AutoField(db_column='frecuencia_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='frecuencia',
            name='nivel',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='id',
            field=models.AutoField(db_column='hardware_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='nombre',
            field=models.CharField(db_column='hardware', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='so',
            field=models.CharField(blank=True, db_column='sistema_operativo', max_length=160, verbose_name='Sistema operativo'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='id',
            field=models.AutoField(db_column='sistema_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='nombre',
            field=models.CharField(db_column='sistema_nombre', max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='id',
            field=models.AutoField(db_column='solucion_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solucion',
            name='nombre',
            field=models.CharField(db_column='titulo', max_length=220, unique=True, verbose_name='Titulo'),
        ),
        migrations.AlterModelTable(
            name='frecuencia',
            table='frecuencia',
        ),
        migrations.AlterModelTable(
            name='hardware',
            table='hardware',
        ),
        migrations.AlterModelTable(
            name='sistema',
            table='sistema',
        ),
        migrations.AlterModelTable(
            name='solucion',
            table='solucion',
        ),
        migrations.CreateModel(
            name='HardwareSistema',
            fields=[
                ('pk', models.CompositePrimaryKey('hardware', 'sistema', blank=True, editable=False, primary_key=True, serialize=False)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errores.hardware')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errores.sistema')),
            ],
            options={
                'verbose_name': 'Hardware / sistema',
                'verbose_name_plural': 'Hardware / sistemas',
                'db_table': 'hardware_sistema',
            },
        ),
        migrations.AddField(
            model_name='hardware',
            name='sistemas',
            field=models.ManyToManyField(blank=True, related_name='hardware', through='errores.HardwareSistema', to='errores.sistema'),
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(db_column='modulo_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='modulo_nombre', max_length=180, verbose_name='Modulo')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='errores.sistema')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'db_table': 'modulo',
                'ordering': ['sistema__nombre', 'nombre'],
                'constraints': [
                    models.UniqueConstraint(fields=('sistema', 'id'), name='uq_modulo_sistema_id'),
                    models.UniqueConstraint(fields=('sistema', 'nombre'), name='uq_modulo_sistema_nombre'),
                ],
            },
        ),
        migrations.RunPython(cargar_modulos_desde_seccion, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sistema',
            name='seccion',
        ),
    ]
