# Generated by Django 5.2.14 on 2026-05-15

import django.db.models.deletion
from django.db import migrations, models


def migrar_datos_error_normalizados(apps, schema_editor):
    Error = apps.get_model('errores', 'Error')
    ErrorPrueba = apps.get_model('errores', 'ErrorPrueba')
    ErrorSolucion = apps.get_model('errores', 'ErrorSolucion')
    Modulo = apps.get_model('errores', 'Modulo')
    Prueba = apps.get_model('errores', 'Prueba')
    Solucion = apps.get_model('errores', 'Solucion')

    for error in Error.objects.all():
        seccion = (getattr(error, 'seccion_app', '') or '').strip()
        if error.sistema_id and seccion and not error.modulo_id:
            modulo, _ = Modulo.objects.get_or_create(sistema_id=error.sistema_id, nombre=seccion)
            error.modulo = modulo
            error.save(update_fields=['modulo'])

        pruebas = (getattr(error, 'pruebas', '') or '').strip()
        if pruebas:
            prueba, _ = Prueba.objects.get_or_create(descripcion=pruebas[:255])
            ErrorPrueba.objects.get_or_create(error=error, prueba=prueba)

        solucion_texto = (error.solucion or '').strip()
        if solucion_texto:
            solucion, _ = Solucion.objects.get_or_create(
                nombre=solucion_texto[:220],
                defaults={'pasos': solucion_texto},
            )
            ErrorSolucion.objects.get_or_create(error=error, solucion=solucion)


def crear_fk_error_modulo_sistema(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == 'mysql':
        schema_editor.execute(
            'ALTER TABLE `error` '
            'ADD CONSTRAINT `fk_error_modulo_sistema` '
            'FOREIGN KEY (`sistema_id`, `modulo_id`) '
            'REFERENCES `modulo` (`sistema_id`, `modulo_id`)'
        )


def borrar_fk_error_modulo_sistema(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == 'mysql':
        schema_editor.execute('ALTER TABLE `error` DROP FOREIGN KEY `fk_error_modulo_sistema`')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('errores', '0002_tablas_catalogo'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE TABLE IF NOT EXISTS `responsable` ('
                        '`responsable_id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, '
                        '`responsable_nombre` varchar(160) NOT NULL UNIQUE, '
                        '`cargo` varchar(120) NOT NULL, '
                        '`contacto` varchar(160) NOT NULL, '
                        '`activo` bool NOT NULL DEFAULT TRUE'
                        ')'
                    ),
                    reverse_sql='DROP TABLE IF EXISTS `responsable`',
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Responsable',
                    fields=[
                        ('id', models.AutoField(db_column='responsable_id', primary_key=True, serialize=False)),
                        ('nombre', models.CharField(db_column='responsable_nombre', max_length=160, unique=True)),
                        ('cargo', models.CharField(blank=True, max_length=120)),
                        ('contacto', models.CharField(blank=True, max_length=160)),
                        ('activo', models.BooleanField(default=True)),
                    ],
                    options={
                        'verbose_name': 'Responsable',
                        'verbose_name_plural': 'Responsables',
                        'db_table': 'responsable',
                        'ordering': ['nombre'],
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name='SolucionResponsable',
            fields=[
                ('pk', models.CompositePrimaryKey('solucion', 'responsable', blank=True, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(blank=True, max_length=120)),
                ('principal', models.BooleanField(default=False)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errores.responsable')),
                ('solucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errores.solucion')),
            ],
            options={
                'verbose_name': 'Solucion / responsable',
                'verbose_name_plural': 'Soluciones / responsables',
                'db_table': 'solucion_responsable',
            },
        ),
        migrations.AddField(
            model_name='error',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errores', to='errores.modulo'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, db_column='actualizado_en'),
        ),
        migrations.AlterField(
            model_name='error',
            name='causa',
            field=models.TextField(blank=True, db_column='causa_problema', verbose_name='Causa del problema'),
        ),
        migrations.AlterField(
            model_name='error',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_column='creado_en'),
        ),
        migrations.AlterField(
            model_name='error',
            name='descripcion',
            field=models.TextField(db_column='error_descripcion', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='error',
            name='id',
            field=models.AutoField(db_column='error_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='error',
            name='imagen_error',
            field=models.TextField(blank=True, db_column='error_imagen', verbose_name='Imagen del error'),
        ),
        migrations.AlterField(
            model_name='error',
            name='solucion',
            field=models.TextField(blank=True, db_column='solucion_texto', verbose_name='Solucion o pasos para resolver'),
        ),
        migrations.AlterField(
            model_name='error',
            name='usuario',
            field=models.TextField(blank=True, db_column='usuario_contexto', verbose_name='Usuario'),
        ),
        migrations.AlterModelTable(
            name='error',
            table='error',
        ),
        migrations.CreateModel(
            name='ErrorPrueba',
            fields=[
                ('pk', models.CompositePrimaryKey('error', 'prueba', blank=True, editable=False, primary_key=True, serialize=False)),
                ('resultado_esperado', models.TextField(blank=True)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errores.error')),
                ('prueba', models.ForeignKey(db_column='prueba_tipica_id', on_delete=django.db.models.deletion.CASCADE, to='errores.prueba')),
            ],
            options={
                'verbose_name': 'Error / prueba',
                'verbose_name_plural': 'Errores / pruebas',
                'db_table': 'error_prueba',
            },
        ),
        migrations.CreateModel(
            name='ErrorSolucion',
            fields=[
                ('pk', models.CompositePrimaryKey('error', 'solucion', blank=True, editable=False, primary_key=True, serialize=False)),
                ('orden', models.IntegerField(default=1)),
                ('notas', models.TextField(blank=True)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errores.error')),
                ('solucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errores.solucion')),
            ],
            options={
                'verbose_name': 'Error / solucion',
                'verbose_name_plural': 'Errores / soluciones',
                'db_table': 'error_solucion',
                'ordering': ['error_id', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='error',
            name='soluciones',
            field=models.ManyToManyField(blank=True, related_name='errores_asociados', through='errores.ErrorSolucion', to='errores.solucion'),
        ),
        migrations.RunPython(migrar_datos_error_normalizados, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='error',
            name='seccion_app',
        ),
        migrations.RemoveField(
            model_name='error',
            name='pruebas',
        ),
        migrations.AddField(
            model_name='error',
            name='pruebas',
            field=models.ManyToManyField(blank=True, related_name='errores', through='errores.ErrorPrueba', to='errores.prueba'),
        ),
        migrations.AddConstraint(
            model_name='error',
            constraint=models.CheckConstraint(condition=models.Q(('modulo__isnull', True), ('sistema__isnull', False), _connector='OR'), name='ck_error_modulo_requiere_sistema'),
        ),
        migrations.RunPython(crear_fk_error_modulo_sistema, borrar_fk_error_modulo_sistema),
    ]
