from django.urls import path
from . import views

app_name = 'errores'

urlpatterns = [
    path('', views.lista_errores, name='lista'),
    path('error/nuevo/', views.crear_error, name='crear'),
    path('error/<int:pk>/', views.detalle_error, name='detalle'),
    path('error/<int:pk>/editar/', views.editar_error, name='editar'),
    path('error/<int:pk>/eliminar/', views.eliminar_error, name='eliminar'),
    path('plataforma/hardware/', views.lista_hardware, name='hardware_lista'),
    path('plataforma/hardware/nuevo/', views.crear_hardware, name='hardware_crear'),
    path('plataforma/hardware/<int:pk>/editar/', views.editar_hardware, name='hardware_editar'),
    path('plataforma/hardware/<int:pk>/eliminar/', views.eliminar_hardware, name='hardware_eliminar'),
    path('plataforma/sistemas/', views.lista_sistemas, name='sistema_lista'),
    path('plataforma/sistemas/nuevo/', views.crear_sistema, name='sistema_crear'),
    path('plataforma/sistemas/<int:pk>/editar/', views.editar_sistema, name='sistema_editar'),
    path('plataforma/sistemas/<int:pk>/eliminar/', views.eliminar_sistema, name='sistema_eliminar'),
    path('responsables/', views.lista_responsables, name='responsable_lista'),
    path('responsables/nuevo/', views.crear_responsable, name='responsable_crear'),
    path('responsables/<int:pk>/editar/', views.editar_responsable, name='responsable_editar'),
    path('responsables/<int:pk>/eliminar/', views.eliminar_responsable, name='responsable_eliminar'),
    path('departamentos/', views.lista_departamentos, name='departamento_lista'),
    path('departamentos/nuevo/', views.crear_departamento, name='departamento_crear'),
    path('departamentos/<int:pk>/', views.detalle_departamento, name='departamento_detalle'),
    path('departamentos/<int:pk>/editar/', views.editar_departamento, name='departamento_editar'),
    path('departamentos/<int:pk>/eliminar/', views.eliminar_departamento, name='departamento_eliminar'),
    path('departamentos/<int:departamento_pk>/responsables/nuevo/', views.crear_responsable_departamento, name='departamento_responsable_crear'),
    path('departamentos/<int:departamento_pk>/responsables/<int:pk>/editar/', views.editar_responsable_departamento, name='departamento_responsable_editar'),
    path('departamentos/<int:departamento_pk>/responsables/<int:pk>/eliminar/', views.eliminar_responsable_departamento, name='departamento_responsable_eliminar'),
    path('pruebas/', views.lista_pruebas, name='prueba_lista'),
    path('pruebas/nuevo/', views.crear_prueba, name='prueba_crear'),
    path('pruebas/<int:pk>/editar/', views.editar_prueba, name='prueba_editar'),
    path('pruebas/<int:pk>/eliminar/', views.eliminar_prueba, name='prueba_eliminar'),
    path('soluciones/', views.lista_soluciones, name='solucion_lista'),
    path('soluciones/nuevo/', views.crear_solucion, name='solucion_crear'),
    path('soluciones/rapida/', views.crear_solucion_rapida, name='solucion_crear_rapida'),
    path('soluciones/<int:pk>/rapida/', views.editar_solucion_rapida, name='solucion_editar_rapida'),
    path('soluciones/<int:pk>/editar/', views.editar_solucion, name='solucion_editar'),
    path('soluciones/<int:pk>/eliminar/', views.eliminar_solucion, name='solucion_eliminar'),
]
